version: '3.8'
services:
  redis:
    container_name: laliga-redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_USER=default
    networks:
      laliga-network:
        aliases:
          - laliga-redis.local
  redis-commander:
    container_name: laliga-redis-commander
    hostname: redis-commander-host
    image: rediscommander/redis-commander:latest
    ports:
        - "8081:8081"
    links:
        - redis
    environment:
      - REDIS_HOSTS=redis
    networks:
      laliga-network:
        aliases:
          - laliga-redis-commander.local
  mongodb:
    container_name: laliga-mongodb
    image: mongo:latest
    ports:
      - "127.0.0.1:27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: mongodb
      MONGO_REPLICA_PORT: 27017
    networks:
      laliga-network:
        aliases:
          - laliga-mongodb.local

  backend:
    container_name: laliga-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - mongodb
    links:
      - redis
      - mongodb
    environment:
      - APP_NAME=la-liga
      - APP_PORT=3001
      - REDIS_HOST=laliga-redis
      - REDIS_PORT=6379
      - REDIS_TTL=1000
      - REDIS_USER=default
      - REDIS_PASSWORD=password
      - MONGODB_URI=mongodb://test:password@laliga-mongodb:27017
      - MONGODB_NAME=la-liga
      - RAPID_API_KEY=${RAPID_API_KEY}
      - LIVESCORE_STANDINGS_HOST=livescore6.p.rapidapi.com
      - LIVESCORE_STANDINGS_ENDPOINT=https://livescore6.p.rapidapi.com/leagues/v2/get-table
      - LALIGA_NEWS_ENDPOINT=https://football-news-aggregator-live.p.rapidapi.com/news/fourfourtwo/laliga
      - LALIGA_NEWS_HOST=football-news-aggregator-live.p.rapidapi.com
    networks:
      laliga-network:
        aliases:
          - laliga-backend.local

networks:
    laliga-network:
      driver: bridge















